default: &default
  adapter: postgresql
  encoding: unicode
  host: deeproots.loc
  username: march-madness-previous-brackets
  password: 9126675918
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: march-madness-previous-brackets
